### ISSUE TITLE
Kink scraper unable to find Scene for no apparent reason

### ISSUE THREAD

**Issue by Ksrx01** [stashapp/CommunityScrapers#1191]
As the title implies, the Kink scraper seems unable to find the scene. Stash is properly configured (CDP path), logs are clean, filename (used by the scraper) are untouched (ex: `10000_shoot_high.mp4`). Even if it seems to be unnecessary, I tried providing the scene title/URL, didn't help.

I tried to see if the URL supposedly generated/used by the scraper leads to the scene's page, which in fact it does.
However it does so only after an age confirmation page, which I think might be the issue.

Does anybody know if this scraper only works with "visible" chrome instances?

**Comment by DogmaDragon** [comment]
Unless they changed something in the last 14 days the headless CDP works with Kink.yml scraper. 

Which action are you using to scrape (Tagger, Scrape with..., by URL)?

**Comment by bnkai** [comment]
If you are using CDP via the path option (path to executable) and not as an address (the headless docker for example) then it might be an issue with the age confirmation you mentioned.
Can you try opening `Kink.yml` with an editor and make sure that the driver section looks like below?
(Make sure you copy paste correctly as the spaces matter)
```yaml
driver:
  useCDP: true
  cookies:
    - Cookies:
        - Name: ct
          Value: 2
          Domain: www.kink.com
          Path: /
# Last Updated December 08, 2022
```
You need to paste the extra part after the `useCDP: true`
