### ISSUE TITLE
Imdb scraper not working: "http error 403:Forbidden"

### ISSUE THREAD

**Issue by ilgiaco** [stashapp/CommunityScrapers#1353]
Imdb scraper not working. I get "http error 403:Forbidden" whenever I do both query and url scraping.

Stash version: v0.20.2
CommunityScrapers version: latest as of today (`047fe0c`)

Other scraper are working well. Can someone confirm the issue?

**Comment by ilgiaco** [comment]
Ok, it seems they are filtering by User-Agent, so just setting it to a different value seems to work for me.
At the end of IMDB.yml file I put this config:
```yml
driver:
  headers:
    - Key: User-Agent
      Value: PostmanRuntime/7.32.3
```
