### ISSUE TITLE
Manyvids Scraper Studio Formatting for FansDB

### ISSUE THREAD

**Issue by A-Random-Mf** [stashapp/CommunityScrapers#1668]
Is it possible for the MV scraper to be adjusted to respect the FansDB studio name format of username (ManyVids)? If yall dont wanna push a whole new update, can you please let me know how to adjust the yml?

**Comment by A-Random-Mf** [comment]
@electricfish1 @Maista6969

**Comment by DogmaDragon** [comment]
```yaml
name: ManyVids

performerByName:
  action: scrapeJson
  queryURL: https://www.manyvids.com/bff/search/autocomplete?keywords={}&contentPref=0
  scraper: performerSearch

performerByURL:
  - action: scrapeJson
    url:
      - https://www.manyvids.com/Profile
    scraper: performerScraper
    queryURL: "{url}"
    queryURLReplace:
      url:
        - regex: .*/Profile/(\d+)/.*
          with: https://www.manyvids.com/bff/profile/profiles/$1

sceneByName:
  action: scrapeJson
  queryURL: https://www.manyvids.com/bff/search/results?keywords={}&contentPref=0
  scraper: sceneSearch

sceneByQueryFragment:
  action: scrapeJson
  scraper: sceneScraper
  queryURL: "{url}"
  queryURLReplace:
    url:
      - regex: ^(https:\/\/www\.manyvids\.com\/Video\/)
        with: https://www.manyvids.com/bff/store/video/
      - regex: /[^/]*/*$
        with: ""

sceneByFragment:
  action: scrapeJson
  scraper: sceneScraper
  queryURL: "https://www.manyvids.com/bff/store/video/{filename}"
  queryURLReplace:
    filename:
      - regex: \.(\w+)$
        with: ""

sceneByURL:
  - action: scrapeJson
    url:
      - https://www.manyvids.com/Video/
    scraper: sceneScraper
    queryURL: "{url}"
    queryURLReplace:
      url:
        - regex: .*?(\d+).*
          with: https://www.manyvids.com/bff/store/video/$1

jsonScrapers:
  performerSearch:
    performer:
      Name: models.#.username
      URL:
        selector: models.#.url
        postProcess:
          - replace:
              - regex: ^
                with: https://www.manyvids.com
      Image: models.#.avatar.url

  performerScraper:
    performer:
      Name: displayName
      Gender: identification
      URL: shortLinkUrl
      Twitter:
        selector: socLnkTwitter
        postProcess:
          - replace:
              - regex: https://www.twitter.com/
                with: ""
      Instagram:
        selector: socLnkInstagram
        postProcess:
          - replace:
              - regex: https://instagram.com/
                with: ""
      Birthdate:
        selector: dob
        postProcess:
          - replace:
              - regex: T.*
                with: ""
          - parseDate: 2006-01-02
      Ethnicity: ethnicity
      Country: location
      HairColor: hairColor
      CareerLength:
        selector: createdAt
        postProcess:
          - replace:
              - regex: '\-.*'
                with: ""
              - regex: "$"
                with: " - Present"
      Image: portrait
      Details: description

  sceneSearch:
    scene:
      Title: vids.#.title
      Code: vids.#.id
      URL:
        selector: "vids.#.{id,slug}.@values"
        postProcess:
          - replace:
              - regex: '\["(\d+)",\s*"([^"]+)"\]'
                with: $1/$2
              - regex: ^
                with: https://www.manyvids.com/Video/
      Image: vids.#.thumbnail.url

  sceneScraper:
    scene:
      Title: data.title
      Details: data.description
      Code: data.id
      URL:
        selector: data.url
        postProcess:
          - replace:
              - regex: ^
                with: https://www.manyvids.com
      Date:
        selector: data.launchDate
        postProcess:
          - replace:
              - regex: T.*
                with: ""
          - parseDate: 2006-01-02
      Image: data.screenshot
      Tags:
        Name: data.tagList.#.label
      Performers:
        Name: data.model.displayName
        URL:
          selector: data.model.profileUrl
          postProcess:
            - replace:
                - regex: ^
                  with: https://www.manyvids.com
      Studio:
        Name: 
          selector: data.model.profileUrl
          postProcess:
          - replace:
              - regex: .*\d+\/(.+)\/
                with: "$1 (ManyVids)"
        URL: data.model.profileUrl
# Last Updated February 22, 2024
```
