### ISSUE TITLE
Improve Model searching for Pornhub

### ISSUE THREAD

**Issue by Joly0** [stashapp/CommunityScrapers#1967]
Hey, i have noticed, that various Models on Pornhub are not found. This is due to the fact, that the original Pornhub.yml file uses this endpoint to search for models "https://www.pornhub.org/pornstars/search?search={}".
This doesnt show all Models, just ones that are listed as pornstars. There are also users, who are uploading stuff, but not listedd as pornstars. By trying out, i found "Lana Bee" for example. 

Though i have found out, that this endpoint gives back correctly the user "https://www.pornhub.org/user/search?username={}"

So there needs some improvement. I thought i could add this myself by changing the first few lines to this:
```
name: Pornhub
performerByName:
  - action: scrapeXPath
    queryURL: https://www.pornhub.com/pornstars/search?search={}
    scraper: performerSearch
  - action: scrapeXPath
    queryURL: https://www.pornhub.org/user/search?username={}
    scraper: modelSearch
```
 but apparentely, the scraper doesnt handle lists very well (it doesnt at all actually, just throws a bunch of unmarshal errors). So there needs another way to add the second one

Edit: I have opened this as an enhancement, but it might also be a bug. I am not sure

 The search should look something like this:
 ```
   modelSearch:
    performer:
      Name: //span[@class="usernameBadgesWrapper"]/a[@class="usernameLink"]/text()
      URL:
        selector: //span[@class="usernameBadgesWrapper"]/a[@class="usernameLink"]/@href
        postProcess:
          - replace:
              - regex: ^
                with: "https://www.pornhub.org"
 ```
 Though i am unable to get this to work, as "performerByName" only accepts one action, queryURL and scraper
