### ISSUE TITLE
`sceneByFragment` cannot find scene for SexLikeReal?

### ISSUE THREAD

**Issue by NormanPriv** [stashapp/CommunityScrapers#2069]
I am new to the scrapers, but I have never successfully got "Scrape with fragment" to work with the SexLikeReal scraper.

It always gives the root URL without finding the URL for the specific scene and getting info for that scene.

Here is the part from `SexLikeReal.yml` that deals with the fragment:

```
sceneByFragment:
  action: scrapeXPath
  # url format: https://www.sexlikereal.com/scenes/{title}-{code}
  # However, the url:
  #     https://www.sexlikereal.com/{code}
  # will redirect to the full url so that is what we will use for scrapping
  queryURL: https://www.sexlikereal.com/{filename}
  queryURLReplace:
    # filename format:
    #   SLR_{stufio:[^_]+}_{title:[^_]+}_{res:\d+p}_{code:\d+}_{vrtype}.{ext}
    #     vrtype: stuff we do not care about but could contain '_'
    filename:
      - regex: (?i)^SLR_.+_\d+p_(\d+)_.*$
        with: $1
      - regex: .*\.[^\.]+$ # if no id is found in the filename
        with: # clear the filename so that it doesn't leak
  scraper: sceneScraper
```

It seems that the regex that replaces filename with the studio code is not working.

**Comment by Maista6969** [comment]
I'd love to make scrapers smarter so they can avoid the unnecessary request if the pattern doesn't match, but that would require some changes to the scraper engine

Does the studio have a new filename format? What's the name of the file you're attempting to scrape?

**Comment by NormanPriv** [comment]
@Maista6969 Here is one example where the scraper cannot generate the scene URL:
`SLR_SLR Originals_Naughty Neighbor_original_47332_FISHEYE190`

On my local copy, I change the pattern as follows and now it works:
```
queryURL: https://www.sexlikereal.com/{filename}
  queryURLReplace:
    # Recognize code from file name
    filename:
      - regex: '.*_(\d+)_.*'
        with: $1
```
Somehow the original pattern is too restrictive?
