### ISSUE TITLE
SpankBang 403

### ISSUE THREAD

**Issue by incognito-bb** [stashapp/CommunityScrapers#2096]
### Error 403: Forbidden
At some point SpankBang updated their bot detection measures to be stricter. I initially noticed this when downloading from the site with yt-dlp.
Instead of downloading like this; 
`yt-dlp https://spankbang.com/8hxfn/video/example+title+of+video` (which now fails).
I now am able to successfully download videos like this; 
`yt-dlp --impersonate edge https://spankbang.com/8hxfn/video/example+title+of+video --legacy-server-connect --no-check-certificates -S "res:1080" --add-metadata -N 4`
I assume similar measures would need to be taken to revive this scraper.

### Are you scraping a scene, gallery, movie, or performer?
Scene
### Scrape with URL? If so, what URLs have you tried?
I have tried scraping via [https://spankbang.com/9cfj0/video/]
### Scrape with fragment? If so, what is the filename / title / studio code?  
Yes, "Video Title [9cfj0].mp4"
### Scrape with name? Give an example you searched for that caused the scraper to fail
N/A

### Please check the logs to see if there are any relevant error messages you can include
```
2024-11-07 12:19:17
Error   
scrapeSingleScene: input: scrapeSingleScene scraper SpankBang: http error 403:Forbidden
2024-11-07 12:19:17
Debug   
[scraper] adding header <User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0)>
2024-11-07 12:19:17
Debug   
After: 9cfj0
2024-11-07 12:19:17
Debug   
Before: 9cfj0
2024-11-07 12:19:17
Debug   
Replace: '.*\.[^\.]+$' with ''
2024-11-07 12:19:17
Debug   
After: 9cfj0
2024-11-07 12:19:17
Debug   
Before: Video Title [9cfj0].mp4
2024-11-07 12:19:17
Debug   
Replace: '.*\[([0-9a-z]{4,})\]\.[^\.]+$' with '$1'
```

**Comment by Muldec** [comment]
I did manage to make it work by using CDP.

However, it only worked on the first scrape. All subsequent scrapes returned ```input: scrapeSceneURL Internal system error. Error <runtime error: index out of range [0] with length 0>``` until I restarted my CDP container.

I updated my CDP image and now I have ```input: scrapeSceneURL parse error: expected string near offset 1563 of 'partitionKey'```

Interrestingly, only with this scraper

**Comment by feederbox826** [comment]
> I updated my CDP image and now I have input: scrapeSceneURL parse error: expected string near offset 1563 of 'partitionKey'

In my experience that's usually an error from trying to scrape the CF error page, but it errors on postProcessing

**Comment by feederbox826** [comment]
Seems to be intermittent now with VPN. First request fails and then other ones go through fine

**Comment by SturmB** [comment]
I need this scraper since SpankBang is the only site I've found that has metadata on Bambi Blaze and her videos. I just learned how to use a CDP, but now I'm getting the same error as @Muldec: `scraper SpankBang: parse error: expected string near offset 4844 of 'partitionKey'`

I do not have the developer chops to fix whatever might be wrong with this scraper. Is there any chance it can be revisited?

**Comment by feederbox826** [comment]
I'm unable to replicate it https://scrape.feederbox.cc/scene?id=LVQg4imB

You need a VPN + CDP to be able to access spankbang, and if you have more than a few requests in a minute, they also ratelimit you which also gives that error.

**Comment by SturmB** [comment]
I only recently learned what a CDP is and deployed one via Docker container. I don't know how to employ a VPN along with it, though. I do have an account with PIA, though. Are there instructions somewhere?

**Comment by feederbox826** [comment]
This feels like too much of a setup https://discourse.stashapp.cc/t/stashapp-vpn-proxy-setup/2063

**Comment by SturmB** [comment]
Welp, I'm still getting errors: `scrapeSingleScene: input: scrapeSingleScene scraper SpankBang: parse error: expected string near offset 4847 of 'partitionKey'`

The services:

```yml
# Stash - https://hotio.dev/containers/stash/
# mkdir -p /docker/appdata/stash
  stash:
    container_name: stash
    image: ghcr.io/hotio/stash
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 9988:9999
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
      - UMASK=002
      - HTTP_PROXY="http://gluetun:8888"
    volumes:
      - /docker/appdata/stash:/config
      - /media/ex-data/media/adult:/data
    networks:
      - solamnia

# CDP - Chrome Debugging Protocol (needed for some of Stash's scrapers) - https://hub.docker.com/r/chromedp/headless-shell
  cdp:
    container_name: cdp
    image: chromedp/headless-shell
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 9222:9222
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
      - UMASK=002
    networks:
      - solamnia

# Gluetun - VPN Proxy for Stash - https://github.com/qdm12/gluetun-wiki/tree/main
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    labels:
      - org.hotio.pullio.update=true
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /docker/appdata/gluetun:/gluetun
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Kentucky/Louisville
      - UMASK=002
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - SERVER_REGIONS=CA Toronto
      - HTTPPROXY=on
      - HTTPPROXY_STEALTH=on
    networks:
      - solamnia
```

And I made sure to add `proxy: http://gluetun:8888` to Stash's `config.yml` file.

What am I missing?
