### ISSUE TITLE
Fix Johnny Rapid Scraper

### ISSUE THREAD

**Issue by MortonBridges** [stashapp/CommunityScrapers#2291]
The Johnny Rapid studio site has undergone some changes since the last version of the scraper:
- New URL format
- Some sort of access control has been implemented

URL to test (new format): https://johnnyrapid.com/videos/jerk-it-and-work-it

Logs show "404" when scraping, even when scraper rewritten to use new URL format.

Navigating via browser brings up a "click-through".  This click-through is not present on subsequent visits to the site.

**Comment by MortonBridges** [comment]
I got so far as changing the URLs for the scene scraper, but the 404 errors persist.

My first attempt to fix the was to check the cookies.  In the browser the scenes seem to load if I set the appropriate "close-warning" cookie to "1".  Attempting to do this in YML didn't help.  Which isn't terribly surprising, since I've had terrible luck dealing with cookies lately.

My second attempt was to use CDP.  That did not help.

Obviously there may be changes to the selectors for the various fields, but until we get past the 404 errors it's not much sense starting on those.

**Comment by feederbox826** [comment]
how did you try implementing cookies? headers or driver cookies

**Comment by MortonBridges** [comment]
> how did you try implementing cookies? headers or driver cookies

Like this:
```
driver:
  cookies:
    - CookieURL: https://johnnyrapid.com
      Cookies:
        - Name: "close-warning"
          Value: "1"
          Domain: "johnnyrapid.com"
          Path: "/"


```

I've also tried to add in all the cookies I see in my browser.  I'm confident I'm doing something wrong, though.  I have no luck with cookies for some reason...
