### ISSUE TITLE
Fine tune FreeonesCommunity xpath performer scraper

### ISSUE THREAD

**Issue by bnkai** [stashapp/CommunityScrapers#66]
Since the NewFreeones scraper is now used internally in stash it needs some more fine tuning.

As mentioned in the discord channel when birthdate was missing the country was also left out
e.g `https://www.freeones.xxx/alexa-thomas/profile`

Making a couple of changes like

```
Birthdate:
   selector: //div[p[text()='Personal Information']]//div//p/a/span[contains(text(),'Born On')]
```
and 
```
Country: //div[p[text()='Personal Information']]//div//p//a[@data-test="link-country"]
```
seems to fix this behaviour

More feedback is welcome

**Comment by bnkai** [comment]
It seems like FakeTits needs adjustment also
`FakeTits: //span[@data-test='link_span_boobs']` 
seems ok

**Comment by halorrr** [comment]
Question on this, with it having completely taken over the old freeones scraper, should this not be renamed to just `Freeones` instead of `NewFreeones`?

**Comment by bnkai** [comment]
Freeones is reserverd for the embeded one.
We could rename it to something else though if desired.

**Comment by halorrr** [comment]
Are there plans to ever fix the embedded one or will it just be phased out? If so I would think this would would eventually just become `Freeones`. 

If the embedded is sticking around then I do thing it could still use a name change, as eventually `New` is no longer that new. Maybe something like `Community Freeones`.

**Comment by halorrr** [comment]
Since Freeones only supports female performers we could take the same method of babepedia, scraping one of the meta properties and regexing to replace it with `female` as the gender

https://github.com/stashapp/CommunityScrapers/blob/ac408b92f6711b1f4915d836007d9820fc875f55/scrapers/Babepedia.yml#L25-L29

**Comment by bnkai** [comment]
> Are there plans to ever fix the embedded one or will it just be phased out? If so I would think this would would eventually just become `Freeones`.
> 
> If the embedded is sticking around then I do thing it could still use a name change, as eventually `New` is no longer that new. Maybe something like `Community Freeones`.

The embedded one is actually ( since the freeones website changes ) this scraper but hardcoded in the stash code. It serves a purpose though as no setup is needed for that.
The community one is also still useful as you can customize  it and then use it.
For the name and gender I think both points are valid. I will have a look tomorrow. If you want make to make a PR you can do that too.

**Comment by bnkai** [comment]
```
Gender:
     selector: //meta[@name="language"]/@name
        replace:
          - regex: language
            with: "Female"
```
seems ok for the gender part

**Comment by bnkai** [comment]
Gender added and scraper renamed to FreeonesCommunity with latest commit.

**Comment by bnkai** [comment]
Freeones.xxx changed again the appearance tab.
From a quick look the following seem to work
```yaml
name: FreeonesCommunity
performerByName:
  action: scrapeXPath
  queryURL: https://www.freeones.xxx/babes?q={}&v=teasers&s=relevance&l=96&m%5BcanPreviewFeatures%5D=0
  scraper: performerSearch
performerByURL:
  - action: scrapeXPath
    url:
      - https://www.freeones.xxx
    scraper: performerScraper

xPathScrapers:
  performerSearch:
    performer:
      Name: //div[@id="search-result"]//p[@data-test="subject-name"]/text()
      URL:
        selector: //div[@id="search-result"]//div[@data-test="teaser-subject"]/a/@href
        replace:
          - regex: ^
            with: https://www.freeones.xxx
          - regex: $
            with: /profile

  performerScraper:
    performer:
      Name: //h1
      URL:
        selector: //a[span[text()="Profile"]]/@href
        replace:
          - regex: ^
            with: https://www.freeones.xxx
      Twitter: //div[p[text()='Follow On']]//div//a[@class='d-flex align-items-center justify-content-center m-2 social-icons color-twitter']/@href
      Instagram: //div[p[text()='Follow On']]//div//a[@class='d-flex align-items-center justify-content-center m-2 social-icons color-telegram']/@href
      Birthdate:
        selector: //div[p[text()='Personal Information']]//div//p/a/span[contains(text(),'Born On')]
        replace:
          - regex: Born On
            with:
          - regex: ","
            with:
        parseDate: January 2 2006
      Ethnicity:
        selector: //div[p[text()='Ethnicity']]//div//p[@class='mb-0 text-center']
        replace:
          - regex: Asian
            with: "asian"
          - regex: Caucasian
            with: "white"
          - regex: Black
            with: "black"
          - regex: Latin
            with: "hispanic"
      Country: //div[p[text()='Personal Information']]//div//p//a[@data-test="link-country"]
      EyeColor: //span[@data-test="link_span_eye_color"]
      Height:
        selector: //span[@data-test="link_span_height"]
        replace:
          - regex: \D+[\s\S]+
            with: ""
      Measurements:
        selector: //span[@data-test="p-measurements"]//a/span
        concat: " - "
        replace:
          - regex: Unknown
            with:
      FakeTits:
        selector: //span[@data-test='link_span_boobs']
        replace:
          - regex: Unknown
            with:
          - regex: Fake
            with: "Yes"
          - regex: Natural
            with: "No"
      CareerLength:
        selector: //div[p[text()='career']]//div//div[@class='timeline-horizontal mb-3']//div//p[@class='m-0']
        concat: "-"
        replace:
          - regex: -\w+-\w+-\w+-\w+-\w+$
            with: ""
      Aliases: //div[p[text()='Aliases']]//div//p[@class='mb-0 text-center']
      Tattoos: //span[@data-test="p_has_tattoos"]
      Piercings: //span[@data-test="p_has_piercings"]
      Image:
        selector: //div[@class='profile-image-container']//a/img/@src
      Gender:
        selector: //meta[@name="language"]/@name
        replace:
          - regex: language
            with: "Female"
# Last updated June 15, 2020

```
