### ISSUE TITLE
ThePornDb.yml broken on apex

### ISSUE THREAD

**Issue by mauroamore** [stashapp/CommunityScrapers#678]
ThePornDb.yml is broken if there is an apex on the title

**Comment by bnkai** [comment]
ThePornDb by default gets the filename and constructs a query from it.
For filenames with `weird` characters you would probably need to add an extra regex to replace the apexed character with the normal one.
eg 
```yaml
      - regex: \.+
        with: "."
      - regex: "á"
        with: "a"
```
Can you provide some samples ? filename/title of the scene and the relevant porndb url?

**Comment by mauroamore** [comment]
maibe is my terrible English.
For apex I mean '

**Comment by bnkai** [comment]
From what i see tpdb just ignores `'` so the above would be `Gape Me While Hes Gone`
In this case I would adjust the regex replace in the scraper to the following 
```yaml
      - regex: "'" 
        with:
      - regex: "[^a-zA-Z\\d\\-._~]" # clean filename so that it can construct a valid url
        with: "." # "%20"
      - regex: \.+
        with: "."
```
