### ISSUE TITLE
MyDirtyHobby scraper retrieves data in "wrong" language

### ISSUE THREAD

**Issue by toby666123** [stashapp/CommunityScrapers#836]
The MyDirtyHobby scraper retrieves all data (especially Title & description) in English although I want to scrape data from a german Performer w/ german title & descriptions.

It seems MyDirtyHobby implemented some sort of "auto-translation" because if you change language on the website Title & Description are being shown in all other languages but poorly translated.

Is it possible to add an option to the scraper (e.g. via Comment/Uncomment) to let the user choose in which language the data shall be retrieved by the scraper?
Or alternatively if that is impossible: Is it possible to release a "german version" of the MyDirtyHobby Scraper and rename the original one to "English Version" or "Standard version"? 

That would be highly appreciated!! Although I retrieve some text now it is just weird for a german performer who only speaks german. :)

**Comment by bnkai** [comment]
From a quick look some selectors need to be adjusted if you want the german texts. You would have to used the german links (starting with `de.`) eg 
`https://de.mydirtyhobby.com/profil/59237982-MellyBunnyLuder/videos/8370242-Pauls-stiefMutter-was-fuer-eine-ausgehungerte-Drecksau`
and modify the parts that dont work
For example tags need to be changed to
```yaml      Tags:
        Name:
          selector: $script
          postProcess:
            - replace:
                - regex: '.*"(?:Categories|Kategorien)","items":\[([^]]+)\].*'
                  with: $1
                - regex: '{"text":"([^"]+)","href":"[^"]+"}'
                  with: $1
          split: ","
```
and  image to 
```yaml
      Image: //meta[@name="og:image"]/@content
```
For the date we would need a list of all the months as they are printed  so we we could regex replace/map them and then parse them.

If you can provide the  above and a list of urls that work/dont work with the selectors needed i can make a PR probably using different selectors when the urls is www.mydirtyhobby.com vs de.dirtyhobby.com (provided that the de links work for  you and you are not redirected due to geolocation issues)
